# Generated by Django 4.2.5 on 2023-09-29 16:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_auther_saleproduct_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_rename_auther_product_employee'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auther',
            new_name='Employee',
        ),
    ]
