# Generated by Django 4.2.5 on 2023-09-29 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proudct_num', models.IntegerField()),
                ('proudct_name', models.CharField(max_length=200)),
                ('proudct_quantity', models.PositiveIntegerField()),
                ('proudct_kind', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.auther')),
            ],
        ),
    ]
