# Generated by Django 4.2.5 on 2023-09-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleproduct',
            old_name='auther',
            new_name='employee',
        ),
    ]
